
services:
  next-prod:
    container_name: next-prod
    build: 
      context: ./web
      target: prod
    image: rafadanam/next-starter
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT="${PORT:-3000}"
      - HOSTNAME="${HOSTNAME:-0.0.0.0}"
    networks:
      - my_network

  nginx:
    build: 
      context: ./nginx
    image: rafadanam/nginx
    ports:
      - 80:80
    networks:
      - my_network
    depends_on:
      - next-prod

networks:
  my_network: