
services:
  next-dev:
    container_name: next-dev
    build: 
      context: ./web
      target: dev
    ports:
      - 3000:3000
    env_file:
      - .env.dev 
    volumes:
      - ./web/src:/usr/src/app/src
      - ./web/public:/usr/src/app/public