
services:
  next-prod:
    container_name: next-prod
    build: 
      context: ./web
      target: prod
    image: rafadanam/next-starter
    ports:
      - 3000:3000
    env_file:
     - .env.prod
    networks:
      - my_network

  nginx:
    build: 
      context: ./nginx
    ports:
      - 80:80
    networks:
      - my_network
    depends_on:
      - next-prod

networks:
  my_network: